bundle:
  groupId: "io.jenkins.tools.custom-war-packager.demo"
  artifactId: "jenkinsfile-runner"
  vendor: "Jenkins project"
  title: "Jenkinsfile Runner demo"
  description: "Jenkinsfile Runner Docker Image, produced by Custom WAR Packager"
buildSettings:
  pom: pom.xml
  pomIgnoreRoot: true
  jenkinsfileRunner:
    source:
      groupId: "io.jenkins"
      artifactId: "jenkinsfile-runner"
      build:
        # Jenkinsfile Runner produces appassembler directory which is not a maven artifact
        #TODO: replace once Jenkinsfile Runner archives runner & CWP is updated
        noCache: true
      source:
        #dir: "/Users/nenashev/Documents/jenkins/tools/jenkinsfile-runner"
        git: https://github.com/jenkinsci/jenkinsfile-runner.git
        commit: c041d2c4e1c14bf93e1a219d9de4a661bd5fa8ae
    docker:
      base: "jenkins/jenkins:2.150.1"
      tag: "jenkins-experimental/cwp-jenkinsfile-runner-demo"
      build: false
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: "2.150.1"
casc:
  - id: "casc"
    source:
      dir: casc.yml
