bundle:
  groupId: "io.jenkins.tools.custom-war-packager.demo"
  artifactId: "jenkinsfile-runner"
  vendor: "Jenkins project"
  title: "Jenkinsfile Runner demo"
  description: "Jenkinsfile Runner Docker Image, produced by Custom WAR Packager"
buildSettings:
  pom: pom.xml
  pomIgnoreRoot: false
  jenkinsfileRunner:
    source:
      groupId: "io.jenkins"
      artifactId: "jenkinsfile-runner"
      build:
        noCache: true
      source:
        git: https://github.com/jenkinsci/jenkinsfile-runner.git
        branch: parent-pom-1.5
    docker:
      base: "jenkins/jenkins:2.150.1"
      tag: "jenkins-experimental/cwp-jenkinsfile-runner-demo"
      build: false
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: "2.150.1"
casc:
  - id: "casc"
    source:
      dir: casc.yml
